using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using TeamTools.Common.Linting;

namespace TeamTools.SSDT.ProjectValidator.Rules.ReportDatasource
{
    [DataType("ReportDatasource")]
    [RuleIdentity("RDS0006", "DATASOURCE_NAME_NODEFAULT")]
    public sealed class DatasourceNameAutoGeneratedRule : BaseDataToolsXmlNodesRule
    {
        private static readonly string NodeSelector = "//RptDataSource";
        private static readonly Regex AutoGeneratedPrefix = new Regex(@"^Datasource[\d\s_-]*$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

        public DatasourceNameAutoGeneratedRule() : base()
        {
        }

        protected override void DoWhenFound(IEnumerable<XElement> nodes)
        {
            foreach (var ds in nodes)
            {
                string datasourceName = ds.Attribute("Name")?.Value;
                if (!string.IsNullOrEmpty(datasourceName) && AutoGeneratedPrefix.IsMatch(datasourceName))
                {
                    HandleNodeError(ds, datasourceName);
                }
            }
        }

        protected override string GetNodeSelectExpression()
        {
            return NodeSelector;
        }
    }
}
