using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using TeamTools.Common.Linting;

namespace TeamTools.SSDT.ProjectValidator.Rules.Reports
{
    [DataType("ReportDesign")]
    [RuleIdentity("RDL0006", "DATASET_NAME_NODEFAULT")]
    public sealed class DatasetNameAutoGeneratedRule : BaseDataToolsXmlNodesRule
    {
        private const string ReportsNamespace = "rdef";
        private static readonly string NodeSelector = $"//{ReportsNamespace}:DataSets/{ReportsNamespace}:DataSet";
        private static readonly Regex AutoGeneratedPrefix = new Regex(@"^Dataset[\d\s_-]*$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

        public DatasetNameAutoGeneratedRule() : base()
        {
            DatasourceNamespace = ReportsNamespace;
        }

        protected override void DoWhenFound(IEnumerable<XElement> nodes)
        {
            foreach (var ds in nodes)
            {
                string datasetName = ds.Attribute("Name")?.Value;
                if (!string.IsNullOrEmpty(datasetName) && AutoGeneratedPrefix.IsMatch(datasetName))
                {
                    HandleNodeError(ds, datasetName);
                }
            }
        }

        protected override string GetNodeSelectExpression()
        {
            return NodeSelector;
        }
    }
}
