using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using TeamTools.Common.Linting;

namespace TeamTools.SSDT.ProjectValidator.Rules.Reports
{
    [DataType("ReportDesign")]
    [RuleIdentity("RDL0009", "DATASOURCE_NAME_NODEFAULT")]
    public sealed class DatasourceReferenceNameAutoGeneratedRule : BaseDataToolsXmlNodesRule
    {
        private const string ReportsNamespace = "rdef";
        private static readonly string NodeSelector = $"//{ReportsNamespace}:DataSources/{ReportsNamespace}:DataSource";
        private static readonly Regex AutoGeneratedPrefix = new Regex(@"^Datasource[\d\s_-]*$", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

        public DatasourceReferenceNameAutoGeneratedRule() : base()
        {
            DatasourceNamespace = ReportsNamespace;
        }

        protected override void DoWhenFound(IEnumerable<XElement> nodes)
        {
            foreach (var ds in nodes)
            {
                string datasourceName = ds.Attribute("Name")?.Value;
                if (!string.IsNullOrEmpty(datasourceName) && AutoGeneratedPrefix.IsMatch(datasourceName))
                {
                    HandleNodeError(ds, datasourceName);
                }
            }
        }

        protected override string GetNodeSelectExpression()
        {
            return NodeSelector;
        }
    }
}
