//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTools.SSDT.ProjectValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamTools.SSDT.ProjectValidator.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string ViolationDetails_DefaultCursorOptionsRule_missing_definition {
            get {
                return ResourceManager.GetString("ViolationDetails_DefaultCursorOptionsRule_missing_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redundant multiple instances.
        /// </summary>
        internal static string ViolationDetails_DefaultCursorOptionsRule_redundant_definition {
            get {
                return ResourceManager.GetString("ViolationDetails_DefaultCursorOptionsRule_redundant_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing {0} option.
        /// </summary>
        internal static string ViolationDetails_SqlProjStructureOptionsRule_missing_option_template {
            get {
                return ResourceManager.GetString("ViolationDetails_SqlProjStructureOptionsRule_missing_option_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redundant multiple {0} option in lines {1}.
        /// </summary>
        internal static string ViolationDetails_SqlProjStructureOptionsRule_redundant_option_in_lines_template {
            get {
                return ResourceManager.GetString("ViolationDetails_SqlProjStructureOptionsRule_redundant_option_in_lines_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redundant multiple {0} option.
        /// </summary>
        internal static string ViolationDetails_SqlProjStructureOptionsRule_redundant_option_template {
            get {
                return ResourceManager.GetString("ViolationDetails_SqlProjStructureOptionsRule_redundant_option_template", resourceCulture);
            }
        }
    }
}
