# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET lib

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.next-ver.outputs.VERSION }}
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      with:
        semver_only: true

    - uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: patch
        
    - name: Prepare next version
      id: next-ver
      run: |
        TAG=${{ steps.bump-semver.outputs.new_version }}
        echo Latest tag: $TAG
        VERSION=${TAG#v}
        echo Next version: $VERSION        
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    
  build:
    name: Build solution
    needs: semver
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        configuration: [Debug, Release]
        dotnet-version: [ '2.0.x', '6.0.x', '8.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Display dotnet version
      run: dotnet --version

    - name: Set version in all AssemblyInfo.cs files
      uses: secondbounce/assemblyinfo-update@v2
      with:
        version: ${{ needs.semver.outputs.next-version }}

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }} # Unique key for the cache
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Install coverlet
      run: |
           dotnet add package coverlet.msbuild --version 6.0.4 &&
           dotnet add package coverlet.collector --version 6.0.4
      working-directory: TeamTools.SSDT.ProjectValidatorTests
          
    - name: Restore dependencies
      run: dotnet restore --p:ContinuousIntegrationBuild=true
      
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }} --p:ContinuousIntegrationBuild=true --p:GenerateAssemblyInfo=false

    - name: Test
      run: >
        dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal
        -p:CollectCoverage=true -p:CoverletOutput=../TestResults/ -p:CoverletOutputFormat=opencover
        /p:ExcludeByFile="TeamTools.TSQL.Common/**"
        --logger "trx;LogFileName=test-results.trx"

    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      if: ${{ hashFiles('TestResults\coverage.opencover.xml') != '' }}
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: TestResults\coverage.opencover.xml
        gist-filename: TeamTools.Linter.SSDT.code-coverage.json
        gist-id: ${{ env.GIST_COVERAGE_ID }}
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
        
    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        auth: ${{ secrets.GIST_AUTH_TOKEN }}
        gistID: ${{ env.GIST_COVERAGE_ID }}
        filename: test.svg
        label: Coverage
        message: ${{ steps.create_coverage_badge.outputs.percentage }}%
        valColorRange: ${{ steps.create_coverage_badge.outputs.percentage }}
        maxColorRange: 100
        minColorRange: 0

    - name: Print code coverage
      if: steps.create_coverage_badge.outcome == 'success'
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"
    
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        path: '$GITHUB_WORKSPACE\TeamTools.SSDT.ProjectValidatorTests\TestResults\test-results.trx,TestResults\*.trx'
        reporter: dotnet-trx
